    - name: Neko-chan-notify
      uses: athul/telewire@master
      if: always()
      with:
        chat: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        status: ${{ job.status }}
      on:
        push:
        pull_request:
          types: [opened,closed]
        issues:
          types: [opened, closed, reopened]
        issue_comment:
          types: [created]
        watch:
          types: [started]
