name: Soc-media api
on: [push, pull_request, issues, issue_comment, watch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Neko-chan-notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        format: markdown
        message: |
          *Project:* socmedia-api
          *Commit Message:* ${{ github.event.head_commit.message }}
          *Commited by:* ${{ github.actor }}
