name: Neko-chan-notify
on: [push, pull_request, issues, issue_comment, watch]
jobs:
  build:
    name: Telegram-Notify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Neko-chan-notify
      uses: athul/telewire@master
      if: always()
      with:
        chat: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        status: ${{ job.status }}
    - name: send default message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.chat }}
        token: ${{ secrets.token }}
