name: Soc-media api
on: [push, pull_request, issues, issue_comment, watch]
jobs:
  build:
    name: Build
    runs-on: ubuntu_latest
    steps:
    - uses: actions/checkout@master
    - name: Neko-chan-notify
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.chat }}
        token: ${{ secrets.token }}
        args: |
          Project: socmedia-api
          Commit Message: ${{ github.event.head_commit.message }}
          Commited by: ${{ github.actor }}
